[package]
name = "max_min"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"]}
rand = "0.9"

[[bench]]
name = "minmax"
harness = false
